.gitattributes

Very trivial PR - just adjusted the auto-language recognition such that the repo is not listed as 'Roff'

Fixed language recognition.

---

xtrack/loss_location_refinement/loss_location_refinement.py

See issue #145: https://github.com/xsuite/xsuite/issues/145
Sorry for not implementing it right away, I didn't know if it was good practice to limit the functionalities we use to ensure retro-compatibility.

changed f-string to ensure python 3.7 compatibility

---

examples/elens_radial_profile/compute_elens_radial_profile_coefficients.py
tests/test_elements.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/elens.h

Implementation of the measured radial electron current density for Hollow electron lenses. If the coefficients for the radial fit are not given the standard scenario of a constant radial electron current density is applied.  Thanks a lot to @ManonBoucard for the nice work!

Measured radial profile elens

---

xtrack/line.py

Tests failed after the change https://github.com/xsuite/xobjects/commit/2445f8e916bc69fe5c374477eed0d488bc8af731.
With this, they are passing (https://github.com/szymonlopaciuk/xsuite/actions/runs/3146408679/jobs/5114820755).

replace get_a_buffer to allocate_buffer

---

tests/test_vs_madx.py
xtrack/line.py
xtrack/survey_from_tracker.py
xtrack/tracker.py

Implemented survey function in tracker.
Still need to test for lhcb2.

implemented survey function in tracker

---

xtrack/general.py
xtrack/twiss.py

fixed twiss.to_pandas

---

tests/test_radiation.py
tests/test_spacecharge_in_ring.py

Retry the tests that are prone to failure due to indeterminism.
Mandatory: 
Optional:

Retry flaky tests

---

xtrack/twiss.py

Closes # .
Fixes xsuite/xsuite#220.
Mandatory: 
Optional:

bugfix, beta0 should be multiplied instead of divided

---

xtrack/mad_loader.py

Fixes xsuite/xsuite#221
Closes # .
Mandatory: 
Optional:

 Fix typo in mad_loader.py

---

tests/test_elements.py
xtrack/beam_elements/elements.py

Fixes https://github.com/xsuite/xsuite/issues/257
Mandatory: 
Optional:

Fix NotImplementedError

---

.gitignore
tests/test_acceleration.py
tests/test_aperture_turn_ele_and_monitor.py
tests/test_apertures.py
tests/test_collective_tracker.py
tests/test_element_internal_record.py
tests/test_elements.py
tests/test_freeze_longitudinal.py
tests/test_full_rings.py
tests/test_ions.py
tests/test_line.py
tests/test_match_and_track_from_element.py
tests/test_match_tune_chroma_cminus.py
tests/test_monitor.py
tests/test_multisetter.py
tests/test_pipeline.py
tests/test_pyht_interface.py
tests/test_radiation.py
tests/test_spacecharge_in_ring.py
tests/test_survey.py
tests/test_tracker.py
tests/test_vs_madx.py

- Add `@for_all_test_contexts` decorator to the relevant tests.
- Add `.DS_Store` files to `.gitignore`
Mandatory: 
Optional:

Add @for_all_test_contexts to the relevant tests

---

xtrack/prebuild_kernels.py

When the flag is set, details on the search will be given on stdout.
Mandatory: 
Optional:

allow debugging by adding a `verbose` flag to `get_suitable_kernel`

---

xtrack/table.py

Support numpy str
Adding iter, repr to rows and cols
Closes # .
Mandatory: 
Optional:

Adding features to Table [wip]

---

tests/test_elements_thick.py
tests/test_slicing.py
xtrack/line.py
xtrack/mad_loader.py

Closes # .
Mandatory: 
Optional:

Slicing with knobs

---

tests/test_twiss.py
xtrack/twiss.py

Add method to save and load Twiss init objects to dictionaries and json files
Mandatory: 
Optional:

Save TwissInit to file

---

tests/test_elements_thick.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/solenoid.h
xtrack/mad_loader.py
xtrack/prebuilt_kernels/_kernel_definitions.json

Implement a thick solenoid in Xsuite.
Mandatory: 
Optional:

Implement a solenoid

---

tests/test_line.py
xtrack/tracker_data.py

Currently if all elements of the line are on the same buffer, the buffer will be reused for tracking (in TrackerData), otherwise a new buffer will be created on the default context.
This has some unexpected side effects in interplay with line modifications. When an element insertion triggers an insertion of a split drifts, those are created on the context of the original drift, but in their own respective buffers (a reasonable default behaviour, managed by `xobjects.HybridClass`). When building a tracker in such a line, the elements are then moved into a new buffer, possibly prompting a change of context (say from OpenMP to CPU serial), and confusing the user.
This PR implements the behaviour that the new buffer will preserve the common context of all elements if there is one.
Closes …

Use common context to create buffer on tracker build if no common buffer

---

examples/toy_ring/007_cut_at_s.py

Add an example for `Line.cut_at_s`.
Mandatory: 
Optional:

Add an example for `cut_at_s`

---

xtrack/multiline/multiline.py

Closes # .
Mandatory: 
Optional:

Attr in twiss

---

examples/dynamic_aperture/000_tracking_for_da.py
examples/fcc_ee_solenoid/004a_prepare_fcc_lattice_with_solenoid.py
examples/fcc_ee_solenoid/004b_correction.py
examples/fcc_ee_solenoid/004c_radiation.py
examples/match_optics/001a_change_beta_star.py
xtrack/_temp/lhc_match/var_limits.py
xtrack/prebuilt_kernels/kernel_definitions.py
xtrack/twiss.py

**Changes:**
- Add missing elements to prebuilt kernels.
- Better estimation of damping partition numbers in twiss.

Relesase 0.56.0

---

ducktrack/elements.py
tests/test_elements.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/linesegmentmap.h

Implemented damping matrix and diffusion matrix in LineSegmentMap
Closes # .
Mandatory: 
- [ x] I have added tests to cover my changes
- [ x] I described my changes in this PR description
Optional:

Damping and diffusion matrix

---

tests/test_prebuild_kernels.py

Closes # .
Mandatory: 
Optional:

Fix tests for prebuilt kernels

---

ducktrack/elements.py
examples/transfer_matrix/005_radiation.py
tests/test_elements.py
tests/test_tracker.py
tests/test_twiss.py
xtrack/__init__.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/linesegmentmap.h
xtrack/general.py
xtrack/line.py
xtrack/linear_normal_form.py
xtrack/match.py
xtrack/tracker.py
xtrack/twiss.py

**Changes:**
- Introduce full ramping and gaussian excitation matrices in `LineSegmentMap`.
- Support `xt.START` and `xt.END` to implicitly define start and end in `Line.twiss()`.
- Introduce `Line.configure_intrabeam_scattering()`.

Release 0.61.0

---

xtrack/twissplot.py

- Introduce `ylim()` e.g.  `twiss.plot("betx bety").ylim(0,10000).savefig("myplot.png")`
Closes # .
Mandatory: 
Optional:

WIP add plot features

---

xtrack/headers/synrad_spectrum.h

**Fix:**
- Avoid underflow condition in SynRad

Fix underflow in synrad

---

examples/orbit_and_tracjectory_correction/004_thread_before_co_corr.py
examples/orbit_and_tracjectory_correction/006_fcc.py
xtrack/trajectory_correction.py

**Changes:**
- Improve performance for orbit correction

Release 0.66.1

---

examples/coupling_knobs/002_check_twiss_complex_cmin.py
examples/rbendrbarc/000_dev.py
examples/twiss/010_coupled_beta.py
tests/test_rbend_rbarc.py
tests/test_twiss.py
xtrack/environment.py
xtrack/line.py
xtrack/twiss.py

**Changes**
- Introduce `c_minus_re`, `c_minus_im` in twiss output.
- Handle `rbend` and `rbarc` flags when setting a bend in the environment.
- Fix in `sinc` function.

Xtrack version 0.69.5

---

tests/test_match_tune_chroma_cminus.py

Implemented a new tunes/chromaticities matching test which uses SciPy's minimize method with the L-BFGS-B algorithm and the new `get_jacobian()` method in the `MeritFunctionView` class to get a gradient for a scalar function.
Needs https://github.com/xsuite/xdeps/pull/67 and https://github.com/xsuite/xdeps/pull/78 to be merged first!
Mandatory: 
Optional:

added test for scalar func

---

tests/test_new_madloader.py

some tests have numerical glitches on the rotations
Closes # .
Mandatory: 
Optional:

add all close to mad loader test

---

tests/test_coasting.py
tests/test_elements.py
tests/test_lhc_match_phase_15.py
tests/test_radiation.py
tests/test_radiation_equilibrium_emittances.py
tests/test_random_gen.py
tests/test_spacecharge_in_ring.py
tests/test_tracker.py

Fix random seeds in non-deterministic tests.
Mandatory: 
Optional:

Fix random seeds in non-deterministic tests

---

examples/twiss/032_twiss_with_collective.py
xtrack/line.py
xtrack/tracker.py
xtrack/twiss.py

**Changes:**
- Fix in `Tracker`: incorrect behavior in collective mode when ele_stop=num_elements
- Fix in `Tracker`: last point not stored by element-by-element monitor 
- Add `include_collective` flag in `Line.twiss`

Collective elements in twiss and fixes in collective tracker

---

xtrack/twiss.py

Added analytical derivatives to twiss functions (still work in progress).
Mandatory: 
Optional:

WIP: Added function to calculate derivatives in twiss

---

tests/test_twiss.py
xtrack/twiss.py

Added test for Twiss Derivatives. Slightly changed interface.

Slightly changed interface, added unittest

---

tests/test_random_gen.py
tests/test_random_gen_exp.py

As in the title.
Mandatory: 
Optional:

Fix more random seeds

---

tests/test_native_madloader.py
xtrack/mad_parser/loader.py
xtrack/mad_parser/madx.lark
xtrack/mad_parser/parse.py

Parse expressions within the native madloader and in particular add support for non-deferred expressions.
Mandatory: 
Optional:

Parse expressions within the native madloader

---

examples/madng_interface/001_play_line.py
tests/test_spin.py
xtrack/twiss.py

**Changes:**
- Add spin tune in twiss calculation

Spin tune in tests

---

xtrack/mad_loader.py

**Changes:**
- Fix in Line.vars.default_to_zero

Fix default_to_zero in cpymad loader
