xsuite/xtrack

xtrack/dress_element.py

In case of inheritance the meta class goes through the bases to find an attribute _xofields

Fixe MetaBeamElement for inheritance

---

tests/test_aperture_turn_ele_and_monitor.py
tests/test_collective_tracker.py
tests/test_dress.py
tests/test_elements.py
tests/test_full_rings.py
xtrack/line.py

New features:
- Use ```get_test_contexts``` from xobjects
- Use non-aligned objects in tracker instances, aligned objects elsewhere

Handle memory alignment

---

examples/twiss/000_twiss.py
tests/test_twiss.py
xtrack/line.py
xtrack/tracker.py
xtrack/twiss_from_tracker.py

**New features**
- Qs added to results of ```Tracker.twiss```.
- ```particle_ref``` can be optionally attached to the line. In that case it can be omitted when calling ```Tracker.twiss``` and ```Tracker.find_closed_orbit```.

Qs in twiss and particle_ref attached to line

---

xtrack/line.py
xtrack/loader_mad.py

**Fixes:**
- "ecollimator" element is recognised by the MAD-X loader.
- Additional mathematical functions can be used in expressions (e.g. sinc).

ecollimator element when importing from MAD-X, additional mathematical functions in expressions

---

xtrack/loader_mad.py

"Fixes"
- MAD-X expressions referring to tables are now skipped
- Error in expression conversion for RFMultipole.lag

Two fixes in loading of mad expressions

---

xtrack/line.py

Fixes in ```Line.merge_consecutive_drift``` and ```Line.merge_consecutive_multipoles```

Fixes in Line.merge_consecutive_drift and Line.merge_consecutive_multipoles

---

xtrack/loader_sixtrack.py

In the loading of the cavity element (under `elif etype == 12:`), the energy was retrieved from `initialconditions[-1]`. This is wrong, as the last row of the INIT block in SixTrack is the energy of the second particles from all pairs (and hence not from the reference particle).
Furthermore, the cavity frequency was calculated from `d2` which should represent the harmonic number but is often zero. The harmonic number is however specified with the SYNC block (which we can count on that it is provided, for in the SixTrack logic the cavities are turned off if the SYNC block is missing). Hence in this pull request the code uses `d2` unless it is zero; in that case the value from the SYNC block is used.
Finally, the reference energy and charge are taken from the SIMU block (or its defaults), …

Bugfix in importing cavities from SixTrack

---

tests/test_tracker.py
xtrack/loader_sixtrack.py
xtrack/tracker.py
xtrack/tracker_src/tracker.h

The following new features are implemented:
1) A stop element can be specified with `ele_stop` (in which case `num_elements` has to be `None`).
Tracking will then go from `ele_start` (defaulting to 0) until `ele_stop`, potentially over several turns.
If `ele_stop` is before `ele_start` we pass `s=0`. This counts as one turn (though inside the `particles`
object the `at_turn` will be at 1 already).
The logic is hence that, when `ele_stop` is used, the last turn will be incomplete.
Examples:
a) `ele_start=IP8`, `ele_stop=IP2`, `num_turns=1`
This means we start at IP8, cross `s=0`, and continue until IP2.
This is less than a full turn.
Particles that died between IP8 and IP1 will be `at_turn=0`.
Particles that died between IP1 and IP2 will be `at_turn=1`.
b) `ele_start=IP8`, `ele_stop=IP2`, …

Partial tracking with collective elements

---

setup.py

With this, one can install xtrack for testing as following:
```bash
cd /path/to/xtrack
pip install -e .[tests]  # will install cpymad and pyHEADTAIL if unavailable
```

add extras_require for installing test dependencies

---

xtrack/pipeline/manager.py

Fix a bug where MPI messages could get confused leading to unpredictable behaviour. Added possibility to print print messages for debugging purposes.

Add message key to pipeline manager to uniquely identify messages

---

xtrack/linear_normal_form.py
xtrack/twiss.py

**Changes:**
- Change a default value ```compute_linear_normal_form(M, symplectify=True, ...)```
- Handle missing fsolve_info in closed orbit search when fsolve is skipped

Release v0.20.3

---

tests/test_monitor.py
xtrack/monitors.py

pzeta variable was not accessible in monitor. Included it to be.
To note that there is a problem if the same is attempted for the energy0 variable. It becomes equal to p0c in the monitor, as if it cannot read mass0 and makes it equal to 0. Very subtle difference of 9e-7%.
Mandatory: 
Optional:

Pzeta in monitor

---

tests/test_spacecharge_in_ring.py
tests/test_tracker.py
xtrack/line.py
xtrack/tracker.py

Improve the handling of {`Tracker`, `Line`}`.particle_ref`:
- add a setter to `Tracker`,
- propagate `particle_ref` on `Line.cycle`,
- serialise `Tracker.particle_ref` in `Tracker.to_binary_file`.
Also done a little reformatting.
Closes xsuite/xsuite#212.
Closes xsuite/xsuite#213.
Closes xsuite/xsuite#215.
Mandatory: 
Optional:

Fix behaviour of `particle_ref` in `Tracker` and `Line`

---

examples/full_ring/007_test_freeze_vars.py
tests/test_full_rings.py
tests/test_spacecharge_in_ring.py
tests/test_tracker.py
xtrack/line.py
xtrack/tracker.py

Add an instance variable `Tracker.config: xdeps.utils.AttrDict` where each field is used to define a C flag at tracker compile time.
Each track kernel is cached with the corresponding config, so that when the user changes the config to a previously seen one, the tracker will not be recompiled again. The above changes imply that trackers will be built on-demand, instead of in the constructor. As a result the `skip` option for `track_kernel` has been removed from the non-collective tracker.
Add new methods `Tracker.freeze_vars` and `Tracker.unfreeze` using the above functionality and thanks to 
On top of #232.
Needs xsuite/xpart#47.
Part of the solution for xsuite/xsuite#206
Mandatory: 
Optional:

Multiple kernels in tracker based on compile-time config

---

tests/test_madloader.py
xtrack/mad_loader.py

Create minimal multipoles order in presence of zero trailing knl in madx
Mandatory: 
Optional:

fix zero trailing

---

tests/test_radiation.py
tests/test_spacecharge_in_ring.py

Introduce the functionality of xsuite/xpart#50 in xtrack.
Depends on xsuite/xpart#50
Mandatory: 
Optional:

add granular flaky_assertions contexts to flaky tests

---

xtrack/tapering.py

If cavities have 0 voltage set, do not use them in RF matching and tapering.

Do not use cavities that have 0 initial voltage for RF matching

---

xtrack/prebuild_kernels.py
xtrack/prebuilt_kernels/_kernel_definitions.json
xtrack/tracker.py

There was a bug that some flags set to False would be retained in the kernel metadata. This fixes that.

fix prebuilt kernel behaviour when False flags set explicitly

---

.gitignore
setup.py
tests/test_prebuild_kernels.py
xtrack/beam_elements/elements.py
xtrack/prebuild_kernels.py
xtrack/prebuilt_kernels/_kernel_definitions.json
xtrack/tracker.py

Using a description of kernels located in `xtrack/prebuilt_kernels/_kernel_definitions.json` precompile `.so` files and their descriptions (+ C code) inside of xtrack, so that when a compatible tracker is encountered again, instead of compiling it again, the existing kernel will be used. In order to precompile the kernels, one must call the function `xtrack.prebuild_kernels:regenerate_kernels.py`.
If a tracker determines that it is compatible with a precompiled kernel, it might need to partially rebuild the line in memory: see the relevant code around `TrackerData`.
Needs xsuite/xobjects#85 and xsuite/xfields#68.
Closes xsuite/xsuite#224.
Mandatory: 
Optional:

allow prebuilding and loading prebuilt kernels

---

xtrack/tracker.py

The `optimize_for_tracking` method is really great! It speeds up simulation significantly.
This PR just adds a parameter to be able to suppress the verbose output, defaulting to the present behaviour.
Mandatory: 
Optional:

Allow to change verbosity level in optimize_for_tracking

---

ducktrack/elements.py
tests/test_elements.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/drift.h

Introduce an exact drift element.
Closes xsuite/xsuite#218.
Mandatory: 
Optional:

exact drift calculation enabled with config flag

---

xtrack/tapering.py
xtrack/tracker.py

Initialize the _beamstrahlung_model variable to avoid situations where it is used/modified without being initialized via tracker.configure_radiation
Following the fixes in 0.25.1, this variable beamstrahlung_model is copied in _build_auxiliary_tracker_with_extra_markers, but this can be used without running tracker.configure_radiation() first, for example in the build_particles method. 
Closes [Xsuite issue #269](https://github.com/xsuite/xsuite/issues/269)
Mandatory: 
Optional:

Initialize the _beamstrahlung_model

---

tests/test_twiss.py

In a single place in `test_twiss.py:test_get_normalized_coordinates` replace a tolerance from 5e-12 to 6e-12, as it seems that the original tolerance is tight enough to fail on certain machines.
Mandatory: 
Optional:

increase tolerance in test_twiss.py:test_get_normalized_coordinates

---

tests/test_elements.py
xtrack/beam_elements/elements.py

When an angle is passed to `SRotation`, `XRotation`, or `YRotation` together with the values of the trigonometric functions, check for consistency, and if it is established, do not recalculate the values to preserve numerical stability.
If an angle is not given, but sufficient number of trigonometric values is, calculate the angle from the given input (and check the input for consistency as well).
Closes xsuite/xsuite#278.
Mandatory: 
Optional:

Do not recalculate trig values if consistent with angle in rotation elements

---

xtrack/__init__.py
xtrack/base_element.py
xtrack/beam_elements/elements.py
xtrack/line.py
xtrack/loss_location_refinement/__init__.py
xtrack/loss_location_refinement/loss_location_refinement.py
xtrack/tracker.py
xtrack/twiss.py

This pull request goes together with xsuite/xpart#67.
- Updated `Marker` to be compatible with `behaves_like_drift` inside `xpart.build_particles`
- Updated logic of flags inside `BeamElement`s
Mandatory: 
Optional:

Behaves like drift

---

tests/test_line.py
xtrack/__init__.py
xtrack/line.py
xtrack/tracker.py

From @freddieknets
1. Added a function `merge_consecutive_apertures()` to the `line` to collapse consecutive apertures: in the case of 3 or more consecutive apertures (only separated by `Marker`s or `Drift`s) that are exactly the same, all are removed except the first and the last
2. Expanded the other simplification methods (`remove_zero_length_drifts()`, `merge_consecutive_drifts()`,  `remove_markers()`, `remove_inactive_multipoles()`, and `merge_consecutive_multipoles()`): added a `keep` option to all, and implemented the `inplace=False` functionality
3. Added two tests for `merge_consecutive_apertures()` 
4. Expanded the existing tests for the other simplification methods, to take the new options for `keep` and `inplace` into account
5. Created two helper functions to the `line`: …

Recreate #310

---

examples/full_ring/007_test_freeze_vars.py
tests/test_collimation.py
tests/test_elements.py
tests/test_full_rings.py
tests/test_overriden_particle.py
tests/test_prebuild_kernels.py
tests/test_tracker.py
xtrack/base_element.py
xtrack/beam_elements/apertures.py
xtrack/beam_elements/elements_src/cavity.h
xtrack/headers/checks.h
xtrack/line.py
xtrack/loss_location_refinement/loss_location_refinement.py
xtrack/monitors/particles_monitor.py
xtrack/multisetter/multisetter.py
xtrack/random/random_src/rutherford.h
xtrack/random/random_src/uniform.h
xtrack/tracker.py
xtrack/tracker_data.py

Adapt xtrack to the new particles classes introduced in xsuite/xpart#73, however do not use the idea of a minitracker proposed in #312.
Replaces #312.
Mandatory: 
Optional:

Add a Particles class for purely longitudinal studies (without "minitracker")

---

tests/test_prebuild_kernels.py

The test was not testing actually loading kernels from a file. This was caused by the fact that a supposedly fresh tracker would reuse the same CPU context, and thus, the previous kernel.
Mandatory: 
Optional:

Fix the test of precompiled kernels

---

examples/optimized_tracker/001_time_tracking_on_gpu.py
tests/test_spacecharge_in_ring.py
xtrack/base_element.py
xtrack/internal_record.py
xtrack/monitors/particles_monitor.h
xtrack/tracker.py

This PR is part of the effort to enable OpenMP support in Xsuite.
In Xtrack, on the OpenMP context we introduce two loops particle loops:
- an outer loop over batches of particles that is the one being paralellised (this is similar to the GPU behaviour, but for batches instead of single particles)
- an inner loop inside of each element, which loops over individual particles, and which allows for potential gains from vectorisation (this is similar to the serial CPU behaviour)
In addition, at the end of each kernel, particles are reorganised such that they conform to the expectations from the serial CPU behaviour. Nevertheless, this behaviour can be disabled by setting `XT_OMP_SKIP_REORGANIZE` in the config of the line (it should be noted that our current test suite passes with this flag …

Enable OpenMP support

---

tests/test_compounds.py
xtrack/line.py

Allow inserting elements into the core of a compound (including to the side). Will fail if attempting to insert in between aperture elements.
Mandatory: 
Optional:

Allow inserting elements into compound core

---

xtrack/monitors/last_turns_monitor.py

Initialization with numpy arrays instead of lists reduces compilation time on some GPU contexts significantly.
`np.zeros(size)` is also cleaner than `[0]*size`
Mandatory: 
Optional:

Improve last_turns_monitor performance

---

tests/test_line.py
tests/test_multiline.py
tests/test_orbit_correction.py
xtrack/line.py
xtrack/multiline/multiline.py

Added a metadata attribute to the Multiline class. This attribute is a dictionary containing the collider configuration, e.g. as in [here](https://github.com/xsuite/example_DA_study/blob/main/master_study/master_jobs/2_configure_and_track/config.yaml). This should be helpful for reproducibility of simulations, allowing to embed the configuration of a collider in the corresponding json file.
A unit test has been implemented, in `test_multiline.py`. Of note, the previous unit test for the Multiline class was highly minimal and merged with the orbit correction test. Consequently, I've split `test_multiline_and_orbit_correction.py` into `test_multiline.py` and `test_orbit_correction.py`. All tests are passing.

Add metadata to multiline

---

xtrack/survey.py

The survey code would fail under Python 3.8 since it used a dictionary merge only introduced in 3.9. This small change makes it backwards compatible.
Also move the deprecation guard for `reversed=True` to the top of the function.

fix survey to be compatible with Python < 3.9

---

examples/nonlinear_tunes/detuning.py
examples/nonlinear_tunes/nonlinear_tunes.py

Adds an example and functions to calculate amplitude detuning and non-linear chromaticity.
Mandatory: 
Optional:

Example of amplitude detuning and non-linear chromaticity calculation

---

tests/test_line.py
xtrack/line.py

Proposed fix for xsuite/xsuite#359 to allow thick element in the sequence.
I added a `refer` parameter to `from_sequence` to mirror the same behaviour in MAD-X, however I made `entry` the default to align with the other behaviours of Xsuite.
Closes xsuite/xsuite#359.
Mandatory: 
Optional:

allow the use of thick elements in a Line.from_sequence

---

tests/test_slicing.py
xtrack/beam_elements/elements.py
xtrack/slicing.py

Add a new slicing option that allows slicing thick elements into more thick elements. For example the scheme `Uniform(2, mode='thick')` will slice a single bend of length 1 into two bends of length 0.5.
Mandatory: 
Optional:

add a slicing mode to slice a thick element into several thick elements

---

xtrack/beam_elements/elements_src/drift.h
xtrack/line.py

This is useful to be able to select between expanded and exact drifts on a beamelement-by-beamelement basis.
Mandatory: 
Optional:

Split Drift into two functions (expanded and exact).

---

xtrack/tracker.py

When on OpenMP context, don't try to load prebuild kernels.
Closes xsuite/xsuite#401.
Mandatory: 
Optional:

When on OpenMP context, don't try to load prebuild kernels

---

examples/match_optics/030_FODO_with_knobs.py

Added a simple example that shows how to define knobs for a lattice created directly in xsuite, which are then used to match the optics between two FODO lines.
There was no example showing how to create and use knobs that can be used with the optimizer object, when the line has been created directly in xsuite, rather than being a deferred expression import from madx. 
Closes # .
Mandatory: 
This change has no effect on any other code, it is a stand-alone example that can be run as is.
Optional:

Simple example that shows how to define knobs for a lattice and use to match

---

tests/test_tracker.py
xtrack/line.py
xtrack/mad_loader.py
xtrack/progress_indicator.py
xtrack/slicing.py
xtrack/tracker.py

Add a common progress indicator functionality to Xtrack. This includes the current progress messages in the madloader, when slicing, and during aperture check, as well as adds an optional progress indicator when tracking. When calling the `Line.track` function a parameter `with_progress` can be specified to enable the progress monitoring.
If `with_progress` is truthy, a progress bar is displayed during tracking. If an integer is provided, it is used as the number of turns between two updates of the progress bar. If True, 100 is taken by default. By default, `with_progress` equals to False and no progress bar is displayed.
If the package [tqdm](https://tqdm.github.io/) is installed it will be used automatically for all these progress indicators. Otherwise, a simple progress report akin to …

Add a progress bar facility to xtrack

---

tests/test_multisetter.py
xtrack/multisetter/multisetter.py

In the multisetter, catch the case when the number of elements is zero. In such a case there is no need to use the kernel at all.
Mandatory: 
Optional:

Fix IndexError in multisetter when elements is empty

---

xtrack/line.py
xtrack/survey.py

Survey calculation
```python
line = ...
survey = line.survey()
```
currently requires a tracker, otherwise it throws 
However, there is no point for this requirement, since [`survey_from_tracker(...)`](https://github.com/xsuite/xtrack/blob/ec6247ba48640bf00a71b4bf11ffa1e3782889c2/xtrack/survey.py#L183C32-L183C32) only uses tracker to do
```python
line = tracker.line
```
and nothing else.
-----
This PR directly passes line to the survey calculation
------
/cc @rahulgsin

Use line directly for survey calculation

---

tests/test_radiation_equilibrium_emittances.py

Increase the tolerance as on some machines the test fails because it's is too tight.

Increase tolerance in test_radiation_equilibrium_emittances

---

tests/test_line.py
xtrack/line.py

Add a feature where derived fields can be specified, e.g., to uniformly extract `k0l` from thick and thin elements by summing up individual `knl` and `k0 * length`.
Closes xsuite/xsuite#426.
Mandatory: 
Optional:

Specify derived fields in Line.attr, such as k0l

---

xtrack/twiss.py

Fixes the sign of the slip factor in the docstring.
Both, [code](https://github.com/xsuite/xtrack/blob/18d16aa2a78e565a54fef4eeb71c209f7131dac7/xtrack/twiss.py#L1114) and physics manual define eta with a negative sign (positive above transition):
$$\eta = -\frac{\Delta f/f}{\Delta p/p}=\alpha_c-\frac{1}{\gamma_0^2}$$
```python
eta = -dzeta[-1]/circumference
alpha = eta + 1/part_on_co._xobject.gamma0[0]**2
```
But in the docstring the minus was missing, leading to confusion as the definition with opposite sign (positive below transition) is also commonly used in literature.
Mandatory: 
Optional:

Fix sign of slip factor (documentation inconsistency)

---

xtrack/beam_elements/elements.py
xtrack/twiss.py

Very small changes:
- `SimpleThinQuadrupole` and `SimpleThinBend` were missing a backtrack flag
- in `twiss`, if particles are lost also their state and the element where they are lost are outputted in the error for easier debugging
Mandatory: 
Optional:

Missing backtrack

---

tests/test_slicing.py
tests/test_tracker.py
xtrack/monitors/particles_monitor.py
xtrack/progress_indicator.py
xtrack/tracker.py

- Fix xsuite/xsuite#435, which was caused by the fact that individual run of `Tracker._track` by default allocates a monitor for the minimum required number of turns.
- Additionally handle `ele_start` and `ele_stop` correctly.
- Add a workaround for a broken progressbar in notebooks. This patch is necessary, because notebook.tqdm has a bug. Until it is fixed, this workaround makes it possible to use tqdm with unit_scale in Jupyter. See issue tqdm/tqdm#1399 and PRs tqdm/tqdm#1528 and tqdm/tqdm#1461.
- Fix a bug when iterating on empty containers with the built-in DefaultProgressIndicator.
Mandatory: 
Optional:

fix bugs related to the progress bar

---

tests/test_madloader.py
xtrack/mad_loader.py

Fix an issue in the madloader which caused octagonal apertures with expressions to not be loaded correctly. Use `tan` provided as an expression function, instead of the one from `numpy`.
Closes xsuite/xsuite#452.
Mandatory: 
Optional:

fix a bug in madloader when importing octagon with expressions

---

examples/compounds/001_compound_transform.py
examples/compounds/002_sliced_compound_transform.py
tests/test_line.py
xtrack/line.py

Add examples of transforming compounds. Fix a bug where tilts/shifts were not showing as part of the compound it the line table.
Mandatory: 
Optional:

Fix: transforms not showing in table; add examples for transforms

---

examples/lhc_thick/004_slice_every_x_meters.py
tests/test_line.py
tests/test_slicing.py
tests/test_thick_lhc.py
xtrack/beam_elements/elements.py
xtrack/line.py
xtrack/slicing.py

Given a list of $s$ coordinates, make cuts in the line at those positions. This uses the slicing module as to not repeat the logic used to preserve compounds. A new slicing scheme called `Custom` is introduces, which allows to cut elements at $s$ positions relative to the start of the element.
Mandatory: 
Optional:

Cut the line at specified s coordinates

---

tests/test_prebuild_kernels.py
xtrack/prebuild_kernels.py
xtrack/prebuilt_kernels/kernel_definitions.py

Fetch the prebuilt kernels in the order they are defined. Specify explicit priority on the prebuilt kernels.
Mandatory: 
Optional:

Fetch prebuilt kernels in the order they are defined

---

tests/test_prebuild_kernels.py
xtrack/base_element.py
xtrack/particles/particles.py
xtrack/prebuild_kernels.py
xtrack/prebuilt_kernels/kernel_definitions.py
xtrack/random/random_generators.py
xtrack/tracker.py

The current implementation of prebuilding kernels for (non-tracker) kernels and the attaching of non-particle kernels to a `BeamElement` do not work (the former will not use prebuilt kernels, and the latter will even raise an error when trying to instantiate such an object). This fix addresses that.
Changes:
- The variable `prebuilt_kernels_path` was not passed correctly to `BeamElement.compile_kernels`, making it fail (as it was then passed to `xo.Struct` which doesn't know the variable).
- The `PerParticlePyMethod` did not have this flag at all, making it skip prebuilt kernels
- When looking for a suitable kernel, an empty config would not find anything, as the prebuilt kernels are always stored with a specific config. Now it defaults to the default config of a `Line`.
- Added …

Fix prebuilt kernels

---

xtrack/prebuilt_kernels/kernel_definitions.py

Added two more kernel definitions, `default_only_xtrack_no_limit` and `default_xcoll_no_limit`, that are needed during the losses interpolation.
Mandatory: 
Optional:

Missing prebuilt kernel for aperture interpolation

---

xtrack/base_element.py
xtrack/tracker.py

For simulations where particles can die early on (and where this happens often), like in loss map simulations, the current Open MP implementation is not optimal, as in some threads more particles will have died than others, and the freed resources are not re-assigned (as we are in a big loop over threads, outside of the loop over turns).
It is probably possible to rewrite the logic completely in order to address this smartly, with the particles in a stack where each thread tracks a single particle for all turns (or only over the non-collective parts in case of a collective tracker), and when finished or dead, the thread takes the next particle from the stack to be tracked. This would also be a smart implementation for tracking with GPUs in this scenario.
But for now, there is a very …

Smarter OpenMP

---

examples/small_rings/t001_check_ps.py
examples/transfer_matrix/002_check_with_twiss.py
examples/twiss/028_ddx_ddqx.py
tests/test_ps_against_ptc.py
tests/test_twiss.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/linesegmentmap.h
xtrack/twiss.py

We add the possibility to specify non-linear chromaticities up to any order in LineSegmentMap.
On top of that we remove the possibility to specify the twiss method in `twiss.get_non_linear_chromaticity`, since the method should always be `'4d'`
Mandatory: 
Optional:

Add non-linear chromaticity to LineSegmentMap

---

xtrack/line.py
xtrack/twiss.py

REQUIRES https://github.com/xsuite/xfields/pull/116
This adds a simple method to the `xtrack.Line` configure the IBS kick element (and potentially also install it first, if provided). It mimicks the API introduced in `xfields.ibs` and passes itself as the line, while transmitting all other parameters.
Users would need to upgrade `xfields` to version `>=0.17.0` to use this.
Mandatory: 
Optional:

Implement the IBS kicks configuration API from Line

---

xtrack/linear_normal_form.py

4th return was missing from documentation
Closes # .
Mandatory: 
Optional:

Update linear_normal_form.py docstring

---

tests/test_twiss.py
xtrack/__init__.py
xtrack/general.py
xtrack/match.py
xtrack/twiss.py

Allow passing `xt.START` to the twiss parameter `start` and `xt.END` to the twiss parameter `end`, provided `reverse=False`.
Mandatory: 
Optional:

Allow (limited) passing of xt.{START, END} to twiss start/end

---

tests/test_elements_thick.py
xtrack/beam_elements/elements.py
xtrack/beam_elements/elements_src/solenoid.h
xtrack/beam_elements/slice_elements.py
xtrack/beam_elements/slice_elements_thick.py

- Add `knl`, `ksl` and related fields to the solenoid element to implement multipolar components.
- Also a small amount of refactoring in `xtrack/beam_elements/slice_elements.py`.
- Also see a comment below.
Mandatory: 
Optional:

Add multipolar components to solenoid

---

xtrack/particles/particles.py

When calling `xt.Particles.from_pandas()` the code internally initialises the class as `cls(**dct)`, however, this does not pass the random generator seeds. If it instead calls  `xt.Particles.from_dict()` this is solved.
Mandatory: 
Optional:

Particles.from_pandas() was not loading random generator seeds

---

xtrack/beam_elements/elements_src/track_solenoid.h

Remove a memory label that is causing a build problem on OpenCL.
Mandatory: 
Optional:

Fix for solenoid radiation on OpenCL (memory label)

---

xtrack/tracker.py

There was a bug when using the multitracker with time dependent variables enables. When the tracking is resumed in the multitracker, the method track_with_collective is called with particles=None and instead a '_session_to_resume' which embeds the particles object. Yet the particles object is needed in the part that is enabled by the time dependent variables. To fix this the assignment of the particles object embeded in the _session_to_resume is assigned to the corresponding variable earlier in a dedicated block. 
Also, the 'log' was not propagated when the tracing was stopped and resumed by the pipeline. This is fixed here.
Closes # .
Mandatory: 
Optional:

Fix issue when using time dependent variables (or logger) with multitracker

---

xtrack/particles/particles.py

Currently when calling `particles.filter(...)` the value of `start_tracking_at_element` in the new particles object is always zero, which is a bug.
Mandatory: 
Optional:

Bugfix: `Particles.filter` does not copy the value of `start_tracking_at_element`

---

xtrack/beam_elements/elements.py

`SecondOrderTaylorMap.from_line()` uses `compute_one_turn_matrix_finite_differences()` which for `start==end` returns a full one-turn response matrix. This is a "surprising" behavior in the context of creating a one-turn map, where one might rather expect an identity map (K=0, R=eye, T=0) in this case.

catch start==end in creation of second-order taylor map

---

tests/test_environment.py
xtrack/environment.py
xtrack/line.py

Introduce `Environment.import_line(line, suffix_for_common_elements=None, line_name=None, overwrite_vars=False)` to allow bringing in lines from other environments/lines into an environment in a way that copies variables and expressions.
Requires xsuite/xdeps#89.
Mandatory: 
Optional:

Add Environment.import_line

---

tests/test_elements_thick.py
tests/test_madloader.py
tests/test_periodic_symmetric_twiss_and_match.py
xtrack/match.py
xtrack/particles/constants.py

In scipy==1.15.0 definitions of constants were updated (notably $m_p$ and $\varepsilon_0$) which caused two kinds of failures in our test suite:
1. In some tests results from Xsuite are compared with the results of MAD-X, which can be incompatible if different constants are used – in those cases we can attempt to fix things by redefining the beam in MAD-X using the new constant.
2. In other tests the change causes some assertions that previously held to no longer do so – we fix those by relaxing tolerances.
This PR makes the tests pass again by applying the above-mentioned fixes.
Mandatory: 
Optional:

Apply fixes and relax some tolerances after `scipy.constant` changes

---

tests/test_environment.py
tests/test_new_madloader.py
xtrack/environment.py
xtrack/line.py
xtrack/mad_parser/parse.py

- Fix an issue of the native madloader, where some boolean flags of elements were not loaded properly, blocking the parsing of some existing MAD-X sequences.
- Add test for xsuite/xsuite#581.
- Add explicit test for `Line.copy_element_from`.
- Minor typos and style.
Mandatory: 
Optional:

Fix flag loading in new madloader; more tests for env.new

---

tests/test_new_madloader.py
xtrack/mad_parser/loader.py
xtrack/mad_parser/madx.lark

Fixes xsuite/xsuite#592.
Mandatory: 
Optional:

Bugfix: badly parsed identifiers in new madloader (parse ^ correctly)

---

tests/test_elements_thick.py
tests/test_match_optics_and_ip_knob.py
tests/test_match_optics_and_ip_knob_new_optimize_api.py

- Fix incompatible Particles context error in test_rbend
- Relax optimizer related tolerances: test_match_optics_and_ip_knob*
Mandatory: 
Optional:

Fixes in tests: incompatible ctx in test_rbend; tolerance in test_match_optics

---

tests/test_attr_replicas_and_slices.py
tests/test_elements_thick.py
tests/test_environment.py
xtrack/beam_elements/elements.py
xtrack/mad_loader.py

Add `angle` as an xofield to the Bend. Make `angle` the invariant quantity: meaning that changes to angle change h, changes to length, change h, and changes to h change the angle.
Mandatory: 
Optional:

Add angle to bend

---

tests/test_particles_pdg.py
xtrack/particles/__init__.py
xtrack/particles/constants.py
xtrack/particles/masses.py
xtrack/particles/particles.py
xtrack/particles/pdg.py

- Updated reference masses for electron, muon, proton, and Pb208 with the latest known values (from PDG 2024). Hardcoded those values to avoid sudden changes when `scipy` updates (as previously those masses were calculated from it). The mass of the proton only differs in the last digit, so tests are not affected.
- Added extra reference masses for some particles (pion, kaon, neutron) and semi-stable (>1s) isotopes of H, He, C, O, Ne, Ar, Fe, Xe, Au, and Pb.
- The masses are now in a dedicated file (`xtrack/particles/masses.py`), for easy and logical access in Python à la `xt.particles.masses.Ne20_MASS_EV`. Kept the `constants.py` file (with its variables pointing to `masses.py`) for backwards compatibility of any scripts that would use it.
- Automatically define the same mass names in the …

Updating masses and moving PDG ID functionality from Xpart

---

tests/test_particles_basics.py
xtrack/particles/particles.py

- Bugfix in `Particles.add_to_energy`. The correct formula is $\Delta p_\tau = \frac{\Delta E}{p_0c}\frac{m_0}{m}$ but $\Delta p_\tau = \frac{\Delta E}{p_0c}\frac{m}{m_0}$ was used.
- Code was correct in C (in `LocalParticle_add_to_energy`), however, it was using a temporary variable `mass_ratio` equal to $\frac{m_0}{m}$ which is confusing as it is the inverse of the same variable in python. Homogenised the naming to the Python one (no practical impact as it was only a temporary variable).
- Adapted `test_python_add_to_energy` in  `test_python_add_to_energy` to assert the correct behaviour (fails with the old behaviour).
- When initialising particles with some masses different from $m_0$, throw an error when neither $\delta\$ or $p_\tau$ are provided. This is to force the user to think of …

Fix add to energy

---

tests/test_radiation_equilibrium_emittances_thick.py

Change assertion values and rtol in `test_radiation_equilibrium_emittances_thick.py`.
Mandatory: 
Optional:

Change assertion values and rtol in `test_radiation_equilibrium_emittances_thick.py`

---

tests/test_trajectory_correcton.py
xtrack/line.py
xtrack/trajectory_correction.py

Added feature to use bounded least squares ([scipy implementation](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.lsq_linear.html)) to perform trajectory correction. If user provides corrector bounds, bounded least squares is used, instead of unbounded least squares (both for SVD and Micado).
Mandatory: 
- [~] All the tests are passing, including my new ones -> all tests passing on test_trajectory_correcton.py
Optional:

feat: trajectory correction with bounds

---

xtrack/headers/track.h

This fixes the memory error currently occurring on CUDA contexts (when `particles_rng.h` is involved).
Mandatory: 
Optional:

Fix memory error on CUDA related to vectorize

---

xtrack/line.py

get_amplitude_detuning_coefficients could lock on 0 tune if there is closed orbit
Closes https://github.com/xsuite/xsuite/issues/653
Mandatory: 
Optional:

Fix get_amplitude_detuning_coefficients

---

tests/test_lhc_match_phase_15.py

This removes the `test_lhc_match_phase_15` as it's not necessary and takes a very long time to run.
Mandatory: 
- [-] I have added tests to cover my changes
- [-] All the tests are passing, including my new ones
Optional:
- [-] I have updated the docs in relation to my changes, if applicable
- [-] I have tested also GPU contexts

Remove test_lhc_match_phase_15 from the GPU test suite

---

tests/test_quadrupole_fringe_ptc.py
xtrack/beam_elements/elements_src/track_mult_fringe.h

Replacing pz with 1+delta in multipole fringe fields, needed for symplecticity of the map. Added test for entrance quadrupole fringe compared to values of PTC, which now agree exactly. The determinant of line.compute_one_turn_matrix_finite_differences(p0)['R_matrix'] does not seem sensitive enough to capture the difference in symplecticity.
Mandatory: 
Optional:

Fix fringe symplecticity

---

tests/test_load.py
xtrack/general.py

Supports:
xt.load("https://acc-models.web.cern.ch/acc-models/lhc/hl16/xsuite/lhc.json.gz")
Mandatory: 
Optional:

adding support of gz from url
